### ISSUE TITLE
manually running `eslint .` blows up

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-password-strength-checker#14]
``` bash
➜  fxa-password-strength-checker git:(issue-3-verbose) eslint .

/Users/stomlinson/development/nvm/v0.10.32/lib/node_modules/eslint/lib/config.js:129
                    throw e;
                          ^
Error: Cannot find module 'eslint-config-fxa/client'
Referenced from: /Users/stomlinson/development/fxa-password-strength-checker/.eslintrc
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at loadConfig (/Users/stomlinson/development/nvm/v0.10.32/lib/node_modules/eslint/lib/config.js:96:48)
    at /Users/stomlinson/development/nvm/v0.10.32/lib/node_modules/eslint/lib/config.js:123:46
    at Array.reduceRight (native)
    at loadConfig (/Users/stomlinson/development/nvm/v0.10.32/lib/node_modules/eslint/lib/config.js:111:36)
    at getLocalConfig (/Users/stomlinson/development/nvm/v0.10.32/lib/node_modules/eslint/lib/config.js:225:23)
    at Config.getConfig (/Users/stomlinson/development/nvm/v0.10.32/lib/node_modules/eslint/lib/config.js:363:22)
```

That file is there, under the node_modules subdirectory:

``` bash
➜  fxa-password-strength-checker git:(issue-3-verbose) cd node_modules/eslint-config-fxa
➜  eslint-config-fxa git:(issue-3-verbose) ls -l
total 48
-rw-r--r--+ 1 stomlinson  staff    17 11 Jun 21:22 LICENSE
-rw-r--r--+ 1 stomlinson  staff  1161 11 Jun 21:21 README.md
-rw-r--r--+ 1 stomlinson  staff   376 20 Jul 23:08 client.js
-rw-r--r--+ 1 stomlinson  staff  1288  1 Jul 02:00 index.js
-rw-r--r--+ 1 stomlinson  staff  1436 29 Jul 11:49 package.json
-rw-r--r--+ 1 stomlinson  staff   114 18 Jun 19:47 server.js
➜  eslint-config-fxa git:(issue-3-verbose)
```

**Comment by TDA** [comment]
@shane-tomlinson 

```
Sai-Pc:passwordStrengthChecker schandramouli$ eslint . 
Sai-Pc:passwordStrengthChecker schandramouli$ 
```

fxa/client is getting loaded for me. Maybe remove the node_modules and re-install?

**Comment by pdehaan** [comment]
This is weird.
@shane-tomlinson should be correct.

You've stumbled upon some gray corner of ESLint.
If you have **eslint** installed globally, it will also look for the **eslint-config-fxa** module globally too, so I'd expect a hard fail if you tempt the linting gods with `$ eslint .`.

The best workaround I've found so far is to just call `eslint .` from the package.json `scripts` section, since it will add the /node_modules/.bin/ to your `$PATH` and everything should "just work(tm)". In fact, it looks like we have that, and @shane-tomlinson can just call `$ npm run lint` if you want to lint the code.
Or, we can use Grunt/Gulp, but that's probably overkill in some cases.

The REAL question here is why this works at all for @TDA, unless he also has the **eslint-config-fxa** module installed globally.

#notabug

**Comment by TDA** [comment]
@pdehaan Seems to be the case, I have it installed globally as well.

```
Sai-Pc:passwordStrengthChecker schandramouli$ npm list -g --depth=0
/Users/schandramouli/.nvm/v0.10.38/lib
├── bower@1.4.1
├── chai@3.0.0
├── eslint@0.23.0
├── eslint-config-fxa@1.8.1
├── express-generator@4.12.4
├── fixpack@2.2.0
├── git-it@1.6.8
├── grunt-cli@0.1.13
├── htmllint@0.2.4
├── htmllint-cli@0.0.4
├── jscs@1.13.1
├── jshint@2.8.0
└── scope-chains-closures@1.0.4
```

**Comment by pdehaan** [comment]
Thanks @TDA. That explains it.

Final answer is:

> "Use `npm run lint` which is just a proxy for `eslint .` but adds the correct things to your `$PATH`."

Closing as "sometimes npm/eslint is funny".
